services:
  homepage:
    container_name: Homepage
    image: gethomepage/homepage:latest
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.189.40:3550,homepage.ashish-syn-nas.synology.me
      NEXTAUTH_URL: https://homepage.ashish-syn-nas.synology.me
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      PUID: 1026
      PGID: 100
      HOMEPAGE_AUTH_ENABLED: true
      HOMEPAGE_AUTH_SECRET: ${homepagesecret}
      HOMEPAGE_EXTERNAL_URL: https://homepage.ashish-syn-nas.synology.me
      HOMEPAGE_AUTH_PASSWORD: ${homepagepass}
      TZ: America/Los_Angeles
      HOMEPAGE_VAR_TRILIUM_KEY: ${TRILIUM_TOKEN}
      HOMEPAGE_VAR_LINKWARDEN_KEY: ${LINKWARDEN_TOKEN}
      HOMEPAGE_VAR_KARAKEEP_KEY: ${KARAKEEP_API_KEY}
      HOMEPAGE_VAR_DOCKHAND_PASSWORD: ${DOCKHAND_PASSWORD}
      HOMEPAGE_VAR_DOCKHAND_API_KEY: ${DOCKHAND_API_KEY}
      HOMEPAGE_VAR_SYNOLOGY_PASSWORD: ${SYNOLOGY_PASSWORD}
    ports:
      - 3550:3000
    volumes:
      - /volume1/docker/homepage:/app/config:rw
      - /volume1/docker/homepage/public:/app/public/images:rw
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    restart: on-failure:5
    networks:
      - default
      - bookorbit-deploy_default

  nas-ssh:
    image: ghcr.io/hello2ashu/nas-ssh:latest
    container_name: nas-ssh
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: bridge
    ports:
      - "${nasssh}"
    environment:
      extra_hosts:
        host.docker.internal:host-gateway
      TTYD_USER: ${TTYD_USER}
      TTYD_PASS: ${TTYD_PASS}
      SSH_USER: homeuser
      SSH_PORT: "22"
    volumes:
      - /volume1/docker/nas-ssh/keys:/keys:ro

networks:
  default: {}
  bookorbit-deploy_default:
    external: true
