
services:
  homepage:
    container_name: Homepage
    image: gethomepage/homepage:latest
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true

    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.189.40:3550,homepage.ashish-syn-nas.synology.me
      PUID: 1026
      PGID: 100
      HOMEPAGE_AUTH_ENABLED: true
      HOMEPAGE_AUTH_SECRET: ${homepagesecret}
      HOMEPAGE_EXTERNAL_URL: https://homepage.ashish-syn-nas.synology.me
      HOMEPAGE_AUTH_PASSWORD: ${homepagepass}
      TZ: America/Los_Angeles

    ports:
      - 3550:3000

    volumes:
      - /volume1/docker/homepage:/app/config:rw
      - /volume1/docker/homepage/public:/app/public/images:rw
      - /var/run/docker.sock:/var/run/docker.sock

    restart: on-failure:5

    networks:
      - default
      - bookorbit-deploy_default

  github-repo-sync:
    image: ghcr.io/hello2ashu/github-repo-sync:latest
    container_name: homepage-github-repo-sync
    restart: unless-stopped

    environment:
      GITHUB_USER: hello2ashu
      HOMEPAGE_GROUP: "Repo List"
      HOMEPAGE_CONFIG: /config/services.yaml
      GITHUB_TOKEN: ${github_pat}
      SYNC_INTERVAL_SECS: "3600"
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}
      PUID: 1026
      PGID: 100
      TZ: America/Los_Angeles

    volumes:
      - /volume1/docker/homepage:/config

networks:
  bookorbit-deploy_default:
    external: true
```
